#!/usr/bin/env ruby

require 'time'

ENV["GIT_DIR"] = ARGV[0] + "/.git"

output = `git for-each-ref --format='%(taggerdate:iso)::%(tag)' 'refs/tags/v*'`
output.each do |e|
  e.chomp!
  date, tag = e.split("::")
  date = Time.parse(date)
  puts "tags[%d / $timeblock] = \"%s\"" % [date.to_i, tag]
end
