#!/usr/bin/env ruby

ENV["GIT_DIR"] = ARGV[0] + "/.git"
input = $stdin
input = IO.popen("git log --pretty=\"format:==%an:%ct==\" --all --name-only --date-order --reverse")

puts "<?xml version=\"1.0\"?>"
puts "<file_events>"
list = []
begin
  while true
    while true
      line = input.readline("\n")
      match = line.match("==([^:]+):([^=]+)==")
      break if not match
      author = match[1]
      date = match[2]
    end
    while true
      break if line == "\n"
      line.chomp!("\n")
      puts "<event date=\"#{date.to_i * 1000}\" author=\"#{author}\" filename=\"/#{line}\"/>"
      line = input.readline("\n")
    end
  end
rescue EOFError
end
puts "</file_events>"
